# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricaoEvento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='participante',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='tickets',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='Evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Evento_Inscricao', to='inscricaoEvento.Evento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='Participante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pessoa_Inscricao', to='inscricaoEvento.Pessoa'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='Ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ticket_Inscricao', to='inscricaoEvento.Ticket'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='validacao',
            field=models.CharField(max_length=40),
        ),
    ]
