# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricaoEvento', '0002_auto_20171030_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricao',
            old_name='Evento',
            new_name='evento',
        ),
        migrations.RenameField(
            model_name='inscricao',
            old_name='Participante',
            new_name='participante',
        ),
        migrations.RenameField(
            model_name='inscricao',
            old_name='Ticket',
            new_name='ticket',
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='validacao',
            field=models.BooleanField(default=True, verbose_name=b'Pagamento Confirmado'),
        ),
    ]
