# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricaoEvento', '0003_auto_20171031_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='evento',
        ),
    ]
